import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import type  {RouterOutputs} from "~/utils/api";
import { SignInButton, useUser} from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser()

  if (!user) return null

  return (
    <div className="flex w-full gap-4">
      <Image src={user.profileImageUrl} alt={`Profile Pic`} width={56} height={56} className="h-14 rounded-full" />
      <input placeholder="Type some emojis!" className="bg-transparent grow outline-none"/>
    </div>
  )
}

// 
type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props: PostWithUser) => {
  const { post, author } = props
  return (
    <div key={post.id} className="flex gap-4 p-4 border-b border-slate-400">
      <Image src={author.profileImageUrl} alt={`${author.username}'s Profile Picture`} width={56} height={56} className="h-14 rounded-full" />
      <div className="flex flex-col">
        <div className="flex text-slate-300">
          <span className="mr-2 font-bold">{`@${author.username}`}</span>
          
          <span className="font-thin">{` · ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

const Home: NextPage = () => {
  const user = useUser()
  const {data, isLoading} = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading ...</div>

  if(!data) return <div>Something wrong</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full h-full  border-x border-slate-400  md:max-w-2xl ">
          <div className="flex border-b border-slate-400 p-4">
            {user.isSignedIn && <CreatePostWizard />}
            {!user.isSignedIn && <SignInButton />}
          </div> 
          <div className="flex flex-col">
            {[...data, ...data]?.map((post) => <PostView {...post} key={post.post.id}/>)}
          </div>
        </div>
        
      </main>
    </>
  );
};

export default Home;
